import type { UIElement } from '@json-render/core';

import { theme } from '@/lib/theme';

/**
 * A customer plan, as a json-render spec.
 *
 * Two halves, and the split is the point.
 *
 * The top half is written by hand against the fields that mean something -
 * who the customer is, which plan, and one meter per entry in `usage` with the
 * buttons that action it. Those buttons are the only interactive part of the
 * screen and they deserve to be deliberate.
 *
 * The bottom half is generated by walking whatever else came back. Any field the
 * API adds shows up there on its own, which is what makes this screen able to
 * "cater for anything we might want to load there" without an edit. It reads as a
 * data view rather than as a designed one, and that is correct: it is showing the
 * SDK's answer, not a shop window.
 */

/**
 * The renderer's own element type, not a local approximation of it.
 *
 * Worth importing rather than restating: `props` is required where it looks
 * optional, and `on` takes an array as readily as a single binding. Writing that
 * out by hand gets it subtly wrong, and the mismatch surfaces as a type error at
 * the one call site rather than as anything informative.
 */
export type SpecElement = UIElement<string, Record<string, unknown>>;

export type Spec = {
  root: string;
  elements: Record<string, SpecElement>;
};

/** one usage counter, as `GET /customer-plans` reports it */
export type UsageEntry = {
  feature_ext_id: string;
  name?: string | null;
  used?: number;
  limit?: number | null;
  interval?: string | null;
  overage_allowed?: boolean | null;
};

/**
 * Keys have to be unique across the whole spec and are never shown, so they are
 * generated rather than named. The hint is there to make a spec readable when it
 * is dumped during debugging.
 */
function builder() {
  const elements: Record<string, SpecElement> = {};
  let next = 0;

  const add = (element: SpecElement, hint = 'el'): string => {
    const key = `${hint}-${next++}`;
    elements[key] = element;
    return key;
  };

  return { elements, add };
}

const label = (
  add: ReturnType<typeof builder>['add'],
  text: string,
  opts: { bold?: boolean; color?: string; size?: string } = {},
) =>
  add(
    {
      type: 'Label',
      props: {
        text,
        bold: opts.bold ?? false,
        color: opts.color ?? theme.colorSecondary,
        size: opts.size ?? 'sm',
      },
    },
    'label',
  );

/** how a value reads in the generic half - never "[object Object]" */
function scalarText(value: unknown): string | null {
  if (value === null) return 'null';
  if (value === undefined) return null;
  if (typeof value === 'string') return value.length ? value : '""';
  if (typeof value === 'number' || typeof value === 'boolean') {
    return String(value);
  }
  // arrays and objects are summarised rather than flattened - a count is useful,
  // a wall of JSON is not
  if (Array.isArray(value)) return `[${value.length}]`;
  if (typeof value === 'object') {
    return `{${Object.keys(value as object).length}}`;
  }
  return null;
}

/**
 * Fields worth not repeating.
 *
 * `usage` has its own controls above, and the rest are either already in the
 * header or are noise on a phone screen.
 */
const HANDLED_FIELDS = new Set(['usage', 'customer', 'name', 'id']);

export function buildCustomerSpec(customer: Record<string, unknown>): Spec {
  const { elements, add } = builder();
  const sections: string[] = [];

  /* ---- who this is, and which plan ---- */

  const planName = String(customer.name ?? 'Customer plan');
  const status = customer.latest_status ? String(customer.latest_status) : null;
  const cust = (customer.customer ?? {}) as Record<string, unknown>;

  const headerChildren = [
    add(
      {
        type: 'Heading',
        props: { text: planName, level: 3, color: theme.colorPrimary },
      },
      'plan-name',
    ),
  ];

  if (cust.email || cust.name) {
    headerChildren.push(
      label(add, `${cust.name ?? ''} ${cust.email ? `· ${cust.email}` : ''}`.trim()),
    );
  }

  headerChildren.push(
    label(
      add,
      [
        `plan #${customer.id}`,
        customer.plan_type ? String(customer.plan_type) : null,
        status,
      ]
        .filter(Boolean)
        .join('  ·  '),
    ),
  );

  sections.push(
    add(
      {
        type: 'Card',
        props: { padding: 12, backgroundColor: theme.bgSecondary },
        children: headerChildren,
      },
      'header',
    ),
  );

  /* ---- the meters, one per usage entry ---- */

  const usage = Array.isArray(customer.usage)
    ? (customer.usage as UsageEntry[])
    : [];

  sections.push(
    add(
      {
        type: 'Heading',
        props: { text: 'Metered usage', level: 4, color: theme.colorPrimary },
      },
      'usage-heading',
    ),
  );

  if (!usage.length) {
    /**
     * An honest empty state. A plan with no metered features is the normal case
     * for a one-time payment - a receipt has nothing to meter - so this says
     * which plan was loaded rather than implying something failed.
     */
    sections.push(
      add(
        {
          type: 'Card',
          props: { padding: 12, backgroundColor: theme.bgSecondary },
          children: [
            label(
              add,
              `This plan carries no metered features, so there is nothing to track against. A ${'subscription'} with a usage-limit rule is what puts counters here.`,
            ),
          ],
        },
        'usage-empty',
      ),
    );
  }

  for (const entry of usage) {
    const featureId = entry.feature_ext_id;
    const used = Number(entry.used ?? 0);
    const limit =
      entry.limit === null || entry.limit === undefined
        ? null
        : Number(entry.limit);

    const atLimit = limit !== null && used >= limit && !entry.overage_allowed;
    const remaining = limit === null ? null : Math.max(limit - used, 0);

    const meterChildren = [
      add(
        {
          type: 'Row',
          props: { justifyContent: 'space-between', alignItems: 'center' },
          children: [
            label(add, entry.name || featureId, {
              bold: true,
              color: theme.colorPrimary,
              size: 'md',
            }),
            add(
              {
                type: 'Badge',
                props: {
                  label: atLimit ? 'limit reached' : `${remaining ?? '∞'} left`,
                  variant: atLimit ? 'danger' : 'default',
                },
              },
              'badge',
            ),
          ],
        },
        'meter-head',
      ),
      label(
        add,
        [
          `${used} of ${limit ?? '∞'} used`,
          entry.interval ? `per ${entry.interval}` : null,
          featureId,
        ]
          .filter(Boolean)
          .join('  ·  '),
      ),
    ];

    // a progress bar needs a ceiling to be a fraction of; an unmetered feature
    // has none, so it gets no bar rather than a full or empty one
    if (limit !== null && limit > 0) {
      meterChildren.push(
        add(
          {
            type: 'ProgressBar',
            props: {
              progress: Math.min(used / limit, 1),
              color: atLimit ? theme.danger : theme.colorAlt,
              trackColor: theme.bgPrimary,
              height: 6,
            },
          },
          'bar',
        ),
      );
    }

    /**
     * The two buttons that do the real work.
     *
     * `on.press` binds to the `trackUsage` action, which the screen wires to
     * `useCustomer().track`. Minus sends -1 because the API takes a signed value
     * and handing consumption back is a legitimate call; neither button ever
     * sends 0, which the API refuses.
     */
    meterChildren.push(
      add(
        {
          type: 'Row',
          props: { gap: 8, alignItems: 'center' },
          children: [
            add(
              {
                type: 'Button',
                props: {
                  label: '− 1',
                  variant: 'secondary',
                  size: 'sm',
                  // nothing to give back at zero, and a negative counter is not
                  // a state the plan should be able to reach from here
                  disabled: used <= 0,
                },
                on: {
                  press: { action: 'trackUsage', params: { featureId, value: -1 } },
                },
              },
              'minus',
            ),
            add(
              {
                type: 'Button',
                props: {
                  label: '+ 1',
                  variant: 'primary',
                  size: 'sm',
                  // the server would refuse this with a 403 anyway - the screen
                  // handles that too - but a dead button says so before the tap
                  disabled: atLimit,
                },
                on: {
                  press: { action: 'trackUsage', params: { featureId, value: 1 } },
                },
              },
              'plus',
            ),
          ],
        },
        'meter-actions',
      ),
    );

    sections.push(
      add(
        {
          type: 'Card',
          props: { padding: 12, backgroundColor: theme.bgSecondary },
          children: meterChildren,
        },
        'meter',
      ),
    );
  }

  /* ---- everything else the plan came back with ---- */

  const rest = Object.entries(customer)
    .filter(([key]) => !HANDLED_FIELDS.has(key))
    .map(([key, value]) => [key, scalarText(value)] as const)
    .filter((pair): pair is readonly [string, string] => pair[1] !== null);

  if (rest.length) {
    sections.push(
      add(
        {
          type: 'Heading',
          props: {
            text: 'Everything else on the plan',
            level: 4,
            color: theme.colorPrimary,
          },
        },
        'rest-heading',
      ),
      add(
        {
          type: 'Card',
          props: { padding: 12, backgroundColor: theme.bgSecondary },
          children: rest.map(([key, value]) =>
            add(
              {
                type: 'Row',
                props: { justifyContent: 'space-between', gap: 12 },
                children: [
                  label(add, key),
                  label(add, value, { color: theme.colorPrimary }),
                ],
              },
              'field',
            ),
          ),
        },
        'rest',
      ),
    );
  }

  const root = add(
    {
      type: 'Column',
      props: { gap: 12, padding: 0 },
      children: sections,
    },
    'root',
  );

  return { root, elements };
}
